-- Additive document registry migration v2; core v1 data remains untouched.
CREATE UNIQUE INDEX IF NOT EXISTS idx_source_identity_tender ON sources(id,tender_id);
CREATE TABLE IF NOT EXISTS tender_inventory_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL REFERENCES tenders(id),
 title TEXT NOT NULL CHECK (length(trim(title)) > 0),
 document_type TEXT NOT NULL, publication_date TEXT,
 language TEXT NOT NULL DEFAULT '', version_label TEXT NOT NULL DEFAULT '',
 supersedes_item_id BIGINT, source_id BIGINT,
 availability TEXT NOT NULL CHECK (availability IN ('AVAILABLE','MISSING')),
 notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 UNIQUE (id,tender_id),
 FOREIGN KEY (source_id,tender_id) REFERENCES sources(id,tender_id),
 FOREIGN KEY (supersedes_item_id,tender_id) REFERENCES tender_inventory_items(id,tender_id),
 CHECK (supersedes_item_id IS NULL OR supersedes_item_id <> id),
 CHECK ((availability='AVAILABLE' AND source_id IS NOT NULL)
     OR (availability='MISSING' AND source_id IS NULL))
);
CREATE INDEX IF NOT EXISTS idx_inventory_tender ON tender_inventory_items(tender_id);
CREATE INDEX IF NOT EXISTS idx_inventory_source ON tender_inventory_items(source_id);
CREATE INDEX IF NOT EXISTS idx_inventory_supersedes ON tender_inventory_items(supersedes_item_id);
CREATE TABLE IF NOT EXISTS evidence_files (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 evidence_id BIGINT NOT NULL REFERENCES evidence(id),
 private_path TEXT NOT NULL UNIQUE,
 sha256 TEXT NOT NULL CHECK (sha256 ~ '^[a-f0-9]{64}$'),
 bytes BIGINT NOT NULL CHECK (bytes > 0),
 filename TEXT NOT NULL CHECK (length(trim(filename)) > 0), uploaded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_evidence_file_record ON evidence_files(evidence_id);
CREATE OR REPLACE FUNCTION tenderos_reject_evidence_file_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION 'Evidence file records are immutable' USING ERRCODE='23514';
END;
$$;
CREATE TRIGGER evidence_files_no_mutation BEFORE UPDATE OR DELETE ON evidence_files
FOR EACH ROW EXECUTE FUNCTION tenderos_reject_evidence_file_mutation();
