-- Additive bounded workflow migration v3; prior source and approvals remain unchanged.
CREATE UNIQUE INDEX IF NOT EXISTS idx_tender_identity_org
  ON tenders(id,organization_id);

CREATE TABLE workflow_jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL,
 organization_id BIGINT NOT NULL,
 workflow_kind TEXT NOT NULL CHECK (workflow_kind='READINESS_REVIEW'),
 processor_kind TEXT NOT NULL CHECK (processor_kind IN ('RULES','LOCAL_MODEL')),
 contract_version TEXT NOT NULL,
 state TEXT NOT NULL CHECK (state IN (
   'WAITING_INPUT','READY','RUNNING','WAITING_HUMAN','COMPLETED',
   'FAILED','CANCELLED','STALE','BUDGET_EXHAUSTED')),
 created_by TEXT NOT NULL,
 idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) BETWEEN 16 AND 128),
 request_sha256 TEXT NOT NULL CHECK (request_sha256 ~ '^[a-f0-9]{64}$'),
 input_manifest TEXT NOT NULL,
 input_sha256 TEXT NOT NULL CHECK (input_sha256 ~ '^[a-f0-9]{64}$'),
 policy_manifest TEXT NOT NULL,
 policy_sha256 TEXT NOT NULL CHECK (policy_sha256 ~ '^[a-f0-9]{64}$'),
 step_runs INTEGER NOT NULL DEFAULT 0 CHECK (step_runs >= 0),
 elapsed_ms BIGINT NOT NULL DEFAULT 0 CHECK (elapsed_ms >= 0),
 external_model_calls INTEGER NOT NULL DEFAULT 0 CHECK (external_model_calls=0),
 model_spend_minor BIGINT NOT NULL DEFAULT 0 CHECK (model_spend_minor=0),
 cancel_requested INTEGER NOT NULL DEFAULT 0 CHECK (cancel_requested IN (0,1)),
 revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0),
 restart_of_job_id BIGINT,
 last_error_code TEXT,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT,
 UNIQUE (tender_id,idempotency_key), UNIQUE (id,tender_id),
 FOREIGN KEY (tender_id,organization_id) REFERENCES tenders(id,organization_id),
 FOREIGN KEY (restart_of_job_id,tender_id) REFERENCES workflow_jobs(id,tender_id)
);

CREATE TABLE workflow_steps (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_id BIGINT NOT NULL REFERENCES workflow_jobs(id),
 task_kind TEXT NOT NULL CHECK (task_kind IN (
   'SOURCE_INSPECT','REQUIREMENT_CANDIDATES','EVIDENCE_RELEVANCE','CITATION_CHECK')),
 task_key TEXT NOT NULL,
 contract_version TEXT NOT NULL,
 executor_label TEXT NOT NULL,
 state TEXT NOT NULL CHECK (state IN (
   'BLOCKED','READY','RUNNING','SUCCEEDED','FAILED','CANCELLED','STALE','NEEDS_OCR')),
 predecessor_step_id BIGINT,
 cursor_json TEXT NOT NULL DEFAULT '{}',
 attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 2),
 lease_owner TEXT, lease_expires_at TEXT,
 fence INTEGER NOT NULL DEFAULT 0 CHECK (fence >= 0),
 input_sha256 TEXT NOT NULL CHECK (input_sha256 ~ '^[a-f0-9]{64}$'),
 elapsed_ms BIGINT NOT NULL DEFAULT 0 CHECK (elapsed_ms >= 0),
 last_error_code TEXT,
 started_at TEXT, completed_at TEXT,
 UNIQUE (job_id,task_key), UNIQUE (id,job_id),
 FOREIGN KEY (predecessor_step_id,job_id) REFERENCES workflow_steps(id,job_id)
);

CREATE TABLE workflow_artifacts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_id BIGINT NOT NULL REFERENCES workflow_jobs(id),
 step_id BIGINT NOT NULL,
 artifact_key TEXT NOT NULL,
 artifact_kind TEXT NOT NULL CHECK (artifact_kind IN (
   'SOURCE_BATCH','REQUIREMENT_CANDIDATES','EVIDENCE_SUGGESTIONS','CITATION_CHECKS','RUN_RECEIPT')),
 schema_version TEXT NOT NULL,
 input_sha256 TEXT NOT NULL CHECK (input_sha256 ~ '^[a-f0-9]{64}$'),
 payload_json TEXT NOT NULL,
 output_sha256 TEXT NOT NULL CHECK (output_sha256 ~ '^[a-f0-9]{64}$'),
 created_at TEXT NOT NULL,
 UNIQUE (job_id,artifact_key), UNIQUE (id,job_id),
 FOREIGN KEY (step_id,job_id) REFERENCES workflow_steps(id,job_id)
);

CREATE TABLE workflow_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_id BIGINT NOT NULL REFERENCES workflow_jobs(id),
 step_id BIGINT,
 actor TEXT NOT NULL, action TEXT NOT NULL,
 event_json TEXT NOT NULL, created_at TEXT NOT NULL,
 FOREIGN KEY (step_id,job_id) REFERENCES workflow_steps(id,job_id)
);

CREATE TABLE workflow_candidate_reviews (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_id BIGINT NOT NULL REFERENCES workflow_jobs(id),
 artifact_id BIGINT NOT NULL,
 candidate_key TEXT NOT NULL,
 disposition TEXT NOT NULL CHECK (disposition IN ('ACCEPTED','REJECTED','DUPLICATE')),
 reviewer TEXT NOT NULL, note TEXT NOT NULL,
 requirement_id BIGINT REFERENCES requirements(id),
 reviewed_at TEXT NOT NULL,
 UNIQUE (job_id,candidate_key),
 FOREIGN KEY (artifact_id,job_id) REFERENCES workflow_artifacts(id,job_id)
);
CREATE INDEX idx_workflow_jobs_tender ON workflow_jobs(tender_id,id);
CREATE INDEX idx_workflow_steps_state ON workflow_steps(job_id,state,id);
CREATE INDEX idx_workflow_events_job ON workflow_events(job_id,id);

CREATE OR REPLACE FUNCTION tenderos_reject_workflow_history_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION 'Workflow history records are immutable' USING ERRCODE='23514';
END;
$$;
CREATE TRIGGER workflow_artifacts_no_mutation BEFORE UPDATE OR DELETE ON workflow_artifacts
FOR EACH ROW EXECUTE FUNCTION tenderos_reject_workflow_history_mutation();
CREATE TRIGGER workflow_events_no_mutation BEFORE UPDATE OR DELETE ON workflow_events
FOR EACH ROW EXECUTE FUNCTION tenderos_reject_workflow_history_mutation();
CREATE TRIGGER workflow_candidate_reviews_no_mutation BEFORE UPDATE OR DELETE ON workflow_candidate_reviews
FOR EACH ROW EXECUTE FUNCTION tenderos_reject_workflow_history_mutation();

CREATE OR REPLACE FUNCTION tenderos_guard_workflow_job_inputs() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 IF ROW(OLD.id,OLD.tender_id,OLD.organization_id,OLD.workflow_kind,OLD.processor_kind,
        OLD.contract_version,OLD.created_by,OLD.idempotency_key,OLD.request_sha256,
        OLD.input_manifest,OLD.input_sha256,OLD.policy_manifest,OLD.policy_sha256,
        OLD.restart_of_job_id,OLD.created_at)
    IS DISTINCT FROM
    ROW(NEW.id,NEW.tender_id,NEW.organization_id,NEW.workflow_kind,NEW.processor_kind,
        NEW.contract_version,NEW.created_by,NEW.idempotency_key,NEW.request_sha256,
        NEW.input_manifest,NEW.input_sha256,NEW.policy_manifest,NEW.policy_sha256,
        NEW.restart_of_job_id,NEW.created_at) THEN
   RAISE EXCEPTION 'Workflow inputs and identity are immutable' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER workflow_jobs_frozen_inputs BEFORE UPDATE ON workflow_jobs
FOR EACH ROW EXECUTE FUNCTION tenderos_guard_workflow_job_inputs();

CREATE OR REPLACE FUNCTION tenderos_guard_workflow_step_inputs() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 IF ROW(OLD.id,OLD.job_id,OLD.task_kind,OLD.task_key,OLD.contract_version,
        OLD.executor_label,OLD.predecessor_step_id,OLD.input_sha256)
    IS DISTINCT FROM
    ROW(NEW.id,NEW.job_id,NEW.task_kind,NEW.task_key,NEW.contract_version,
        NEW.executor_label,NEW.predecessor_step_id,NEW.input_sha256) THEN
   RAISE EXCEPTION 'Workflow task inputs and identity are immutable' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER workflow_steps_frozen_inputs BEFORE UPDATE ON workflow_steps
FOR EACH ROW EXECUTE FUNCTION tenderos_guard_workflow_step_inputs();

CREATE OR REPLACE FUNCTION tenderos_guard_workflow_review_requirement() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.requirement_id IS NOT NULL AND NOT EXISTS (
   SELECT 1 FROM requirements r JOIN workflow_jobs j ON r.tender_id=j.tender_id
   WHERE r.id=NEW.requirement_id AND j.id=NEW.job_id
 ) THEN
   RAISE EXCEPTION 'Reviewed requirement must belong to the workflow tender' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER workflow_review_requirement_scope BEFORE INSERT ON workflow_candidate_reviews
FOR EACH ROW EXECUTE FUNCTION tenderos_guard_workflow_review_requirement();

CREATE OR REPLACE FUNCTION tenderos_preserve_workflow_review_requirement_scope() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 IF EXISTS (
   SELECT 1 FROM workflow_candidate_reviews r JOIN workflow_jobs j ON j.id=r.job_id
   WHERE r.requirement_id=OLD.id AND j.tender_id<>NEW.tender_id
 ) THEN
   RAISE EXCEPTION 'Reviewed requirement must remain in the workflow tender' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER workflow_review_preserve_requirement_scope BEFORE UPDATE OF tender_id ON requirements
FOR EACH ROW EXECUTE FUNCTION tenderos_preserve_workflow_review_requirement_scope();
