-- Additive v4 manually recorded commercial operations. No payment/provider calls.
CREATE TABLE IF NOT EXISTS service_intakes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL UNIQUE REFERENCES tenders(id),
 scope TEXT NOT NULL, exclusions TEXT NOT NULL DEFAULT '',
 agreed_inventory_ids_json TEXT NOT NULL, due_at TEXT,
 quoted_fee_minor BIGINT CHECK (quoted_fee_minor IS NULL OR quoted_fee_minor >= 0),
 currency TEXT NOT NULL CHECK (currency='BDT'), reviewer TEXT NOT NULL,
 checklist_json TEXT NOT NULL, actor TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS commercial_ledger (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL REFERENCES tenders(id),
 kind TEXT NOT NULL CHECK (kind IN ('RECEIPT','DIRECT_COST','REFUND','REVERSAL')),
 amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
 currency TEXT NOT NULL CHECK (currency='BDT'), reverses_entry_id BIGINT,
 idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL,
 reference TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', actor TEXT NOT NULL, created_at TEXT NOT NULL,
 UNIQUE (id,tender_id), UNIQUE (tender_id,idempotency_key), UNIQUE (tender_id,kind,reference),
 FOREIGN KEY (reverses_entry_id,tender_id) REFERENCES commercial_ledger(id,tender_id),
 CHECK ((kind IN ('RECEIPT','DIRECT_COST') AND reverses_entry_id IS NULL)
     OR (kind IN ('REFUND','REVERSAL') AND reverses_entry_id IS NOT NULL)),
 CHECK (reverses_entry_id IS NULL OR reverses_entry_id <> id)
);
CREATE INDEX IF NOT EXISTS idx_commercial_ledger_tender ON commercial_ledger(tender_id,id);
CREATE INDEX IF NOT EXISTS idx_commercial_ledger_original ON commercial_ledger(reverses_entry_id);
CREATE TABLE IF NOT EXISTS diagnostic_releases (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL REFERENCES tenders(id),
 release_version BIGINT NOT NULL CHECK (release_version > 0),
 idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL,
 snapshot_json TEXT NOT NULL, snapshot_sha256 TEXT NOT NULL CHECK (snapshot_sha256 ~ '^[a-f0-9]{64}$'),
 currency_fingerprint TEXT NOT NULL CHECK (currency_fingerprint ~ '^[a-f0-9]{64}$'),
 template_version TEXT NOT NULL, actor TEXT NOT NULL, reviewer TEXT NOT NULL, created_at TEXT NOT NULL,
 UNIQUE (tender_id,release_version), UNIQUE (tender_id,idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_diagnostic_releases_tender ON diagnostic_releases(tender_id,id);
CREATE OR REPLACE FUNCTION tenderos_reject_commercial_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION 'Commercial ledger entries and diagnostic releases are immutable' USING ERRCODE='23514';
END;
$$;
CREATE TRIGGER commercial_ledger_no_mutation BEFORE UPDATE OR DELETE ON commercial_ledger
FOR EACH ROW EXECUTE FUNCTION tenderos_reject_commercial_mutation();
CREATE TRIGGER diagnostic_releases_no_mutation BEFORE UPDATE OR DELETE ON diagnostic_releases
FOR EACH ROW EXECUTE FUNCTION tenderos_reject_commercial_mutation();
