-- TenderOS persistent pilot schema v1. Apply with migrate_postgres.py only.
-- Integer flags and ISO date/time TEXT preserve local API/hash semantics.
CREATE TABLE IF NOT EXISTS organizations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS tenders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 title TEXT NOT NULL, buyer TEXT, notice_id TEXT, source_url TEXT,
 deadline TEXT, created_at TEXT NOT NULL,
 source_scope_reviewer TEXT, source_scope_note TEXT,
 source_scope_at TEXT, source_scope_fingerprint TEXT
);
CREATE TABLE IF NOT EXISTS sources (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL REFERENCES tenders(id),
 name TEXT NOT NULL, sha256 TEXT NOT NULL CHECK (sha256 ~ '^[a-f0-9]{64}$'),
 bytes BIGINT NOT NULL CHECK (bytes >= 0), private_path TEXT NOT NULL UNIQUE,
 pages INTEGER NOT NULL CHECK (pages >= 0), uploaded_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS evidence (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 label TEXT NOT NULL, reference TEXT NOT NULL, expires_on TEXT,
 verified SMALLINT NOT NULL DEFAULT 0 CHECK (verified IN (0,1)),
 verification_note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS requirements (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL REFERENCES tenders(id),
 source_id BIGINT REFERENCES sources(id),
 source_page INTEGER CHECK (source_page >= 1), source_quote TEXT,
 text TEXT NOT NULL, mandatory SMALLINT CHECK (mandatory IN (0,1)),
 reviewed SMALLINT NOT NULL DEFAULT 0 CHECK (reviewed IN (0,1)),
 extraction_method TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'UNKNOWN' CHECK (status IN ('UNKNOWN','VERIFIED','PARTIAL','NOT_HELD')),
 evidence_id BIGINT REFERENCES evidence(id), notes TEXT NOT NULL DEFAULT '',
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS decisions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT NOT NULL REFERENCES tenders(id),
 decision TEXT NOT NULL CHECK (decision IN ('BID','NO_BID','HOLD')),
 reviewer TEXT NOT NULL, rationale TEXT NOT NULL,
 decision_snapshot TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tender_id BIGINT REFERENCES tenders(id), actor TEXT NOT NULL,
 action TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pilot_metrics (
 tender_id BIGINT PRIMARY KEY REFERENCES tenders(id),
 quoted_bdt DOUBLE PRECISION CHECK (quoted_bdt >= 0),
 paid_bdt DOUBLE PRECISION CHECK (paid_bdt >= 0),
 baseline_minutes DOUBLE PRECISION CHECK (baseline_minutes >= 0),
 actual_minutes DOUBLE PRECISION CHECK (actual_minutes >= 0),
 decision_changed SMALLINT CHECK (decision_changed IN (0,1)),
 repeat_customer SMALLINT CHECK (repeat_customer IN (0,1)),
 benchmark_minutes DOUBLE PRECISION CHECK (benchmark_minutes >= 0),
 notes TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tender_org ON tenders(organization_id);
CREATE INDEX IF NOT EXISTS idx_source_tender ON sources(tender_id);
CREATE INDEX IF NOT EXISTS idx_req_tender ON requirements(tender_id);
CREATE INDEX IF NOT EXISTS idx_req_source ON requirements(source_id);
CREATE INDEX IF NOT EXISTS idx_req_evidence ON requirements(evidence_id);
CREATE INDEX IF NOT EXISTS idx_evidence_org ON evidence(organization_id);
CREATE INDEX IF NOT EXISTS idx_decision_tender ON decisions(tender_id);
CREATE INDEX IF NOT EXISTS idx_audit_tender ON audit_events(tender_id);
